from functools import partial
import numpy as np
import jax
import jax.numpy as jnp
from simsopt._core import Optimizable
from pyevtk.hl import gridToVTK  # pip install pyevtk

# ---------------------------------------------------------------------------
# Welded-pipe helical vessel SDF whose degrees of freedom are the DISCRETE xyz
# node positions of a piecewise-linear (polyline) centreline -- NOT Fourier
# harmonics. This is a complete rewrite of the old harmonic-based version and
# follows the same shape as the other SDFs in this package (module-level pure
# functions + a thin Optimizable class exposing self.pure / quadratic_threshold
# / quadratic_distance / eval / rz_bounds / to_vtk), so it is a drop-in vessel
# for VesselDistance and round-trips through the array/prefix.sh design JSONs.
#
# CENTRELINE (piecewise-linear, closed loop of ``nseg`` legs):
#   The loop is nfp-fold rotationally symmetric (and optionally stellarator
#   symmetric), exactly like the smooth CurveXYZFourierSymmetries centreline it
#   replaces. The FREE dofs are only the node positions in the fundamental
#   domain; the rest of the loop is generated by the symmetry group:
#     - rotation  Q = Rot_z(2*pi*ntor/nfp)  maps one field period to the next
#       (from C(t+1/nfp) = Q C(t) for the harmonic centreline),
#     - stellarator symmetry  S = diag(1,-1,-1)  with the reflection isometry
#       R = Q S  (from C(1/nfp - t) = Q S C(t)) folds a field period in half.
#   Free nodes sit at the cell centres t = (j+1/2)/nseg of the fundamental
#   domain, so NO node lands on a symmetry plane and every free node keeps all
#   three coordinates free (no partial/pinned dofs). Node counts:
#     stellsym=False:  n_free = nseg/nfp        (one field period)
#     stellsym=True:   n_free = nseg/(2*nfp)    (half a field period)
#   so nseg must be divisible by nfp (2*nfp when stellsym).
#
# TUBE (exact mitred welds, unchanged idea from the old version):
#   Each of the nseg legs is a straight PIPE of radius rr, cut at each joint by
#   the angle-bisector plane and welded to its neighbour. A leg is the CSG
#   intersection (max of SDFs) of its infinite cylinder and its two outward
#   bisector half-spaces; the tube is the union (min) of the legs. For a loop
#   whose turns stay away from a 180 deg reversal this is an EXACT signed
#   distance function. The bisector normalisation is guarded so a degenerate
#   (near-reversal) joint cannot produce a NaN gradient; the geometric penalty
#   below keeps the optimiser inside the valid regime.
#
# DOF LAYOUT (flat vector `params`, all FREE):
#   params = concat([ node_0(x,y,z), ..., node_{n_free-1}(x,y,z),  rr ])
# so the last entry is the (free) constant pipe radius rr and everything before
# it is the fundamental-domain node block, row-major.
# ---------------------------------------------------------------------------


# Turn-angle cap for the mitre welds: turns beyond this approach the degenerate
# 180 deg reversal where the bisector is ill-defined. 150 deg is generous (a
# right-angle quadrilateral, nseg=4, sits comfortably inside) while still fencing
# off the reversal; the mitre-interference term does the finer exactness work.
MAX_TURN_DEG = 150.0
_COS_MIN_TURN = float(np.cos(np.radians(MAX_TURN_DEG)))   # cos(150 deg) ~ -0.866


def _rot_z(theta):
    """3x3 rotation about the z-axis by angle ``theta`` (jax array)."""
    c, s = jnp.cos(theta), jnp.sin(theta)
    return jnp.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


def _unpack(params):
    """Split the flat dof vector into the fundamental-domain nodes (n_free, 3)
    and the constant pipe radius rr. n_free = (len(params)-1)//3."""
    n_free = (params.shape[0] - 1) // 3
    nodes = params[:3 * n_free].reshape(n_free, 3)
    rr = params[3 * n_free]
    return nodes, rr


def _all_joints(nodes, nfp, ntor, stellsym):
    """Generate the full ordered list of ``nseg`` centreline joints (nseg, 3)
    from the fundamental-domain ``nodes`` by applying the symmetry group.

    Ordering follows increasing curve parameter t in [0,1): within field period
    0 the free nodes cover t in (0, 1/(2*nfp)) [stellsym] or (0, 1/nfp), the
    stellsym reflection R=Q S covers the complementary half in reverse, and the
    nfp rotations Q^m tile the remaining field periods."""
    alpha = 2.0 * jnp.pi * ntor / nfp
    Q = _rot_z(alpha)
    if stellsym:
        S = jnp.diag(jnp.array([1.0, -1.0, -1.0]))
        R = Q @ S                              # reflection isometry, t -> 1/nfp - t
        refl = (R @ nodes.T).T                 # images of the free nodes
        half = jnp.concatenate([nodes, refl[::-1]], axis=0)   # one full field period
    else:
        half = nodes                           # one full field period
    blocks = [(_rot_z(m * alpha) @ half.T).T for m in range(nfp)]
    return jnp.concatenate(blocks, axis=0)


def cyl_sdf(p, P0, u, rad):
    """SDF of an INFINITE straight cylinder: axis through P0 along unit dir u,
    radius rad. 'Perpendicular distance from the axis minus the radius'."""
    v = p - P0
    proj = jnp.sum(v * u, axis=-1, keepdims=True) * u
    return jnp.linalg.norm(v - proj, axis=-1) - rad


def _safe_normalize(v, fallback):
    """Row-wise normalise (n,3) vectors; where the norm is ~0 (a degenerate
    near-reversal joint) fall back to the given unit direction instead of
    dividing by zero, keeping the value and its gradient finite."""
    n = jnp.linalg.norm(v, axis=-1, keepdims=True)
    safe = jnp.where(n > 1e-9, n, 1.0)
    return jnp.where(n > 1e-9, v / safe, fallback)


def _leg_geometry(P):
    """From the ordered closed joint list ``P`` (nseg, 3) return, per straight
    leg k (axis P_k -> P_{k+1}, wrapping):

        A       : (nseg, 3)  leg start joint  P_k
        B       : (nseg, 3)  leg end   joint  P_{k+1}
        u       : (nseg, 3)  unit leg direction
        n_start : (nseg, 3)  OUTWARD bisector normal at the START joint
        n_end   : (nseg, 3)  OUTWARD bisector normal at the END   joint

    The bisector at a joint between legs of direction u_prev and u_next has
    normal along (u_prev + u_next). Each normal is oriented so the leg body is
    on its NEGATIVE side (matching cyl_sdf's sign): the outward start normal
    OPPOSES u, the outward end normal ALIGNS with u. Adjacent legs share each
    bisector plane with opposite orientation, so the welded faces coincide."""
    A = P
    B = jnp.roll(P, -1, axis=0)
    u = _safe_normalize(B - A, jnp.array([1.0, 0.0, 0.0]))
    uprev = jnp.roll(u, 1, axis=0)
    unext = jnp.roll(u, -1, axis=0)
    n_start = _safe_normalize(uprev + u, u)
    n_end = _safe_normalize(u + unext, u)
    s_start = jnp.sum(n_start * u, axis=-1, keepdims=True)
    s_end = jnp.sum(n_end * u, axis=-1, keepdims=True)
    n_start = jnp.where(s_start > 0, -n_start, n_start)
    n_end = jnp.where(s_end > 0, n_end, -n_end)
    return A, B, u, n_start, n_end


def _sdf_mitre(pts, A, B, u, n_start, n_end, rr):
    """Exact mitre: each leg is the CSG intersection (max) of its infinite
    cylinder and its two outward bisector half-spaces; the tube is the union
    (min) of the legs."""
    def one(p):
        d_cyl = jax.vmap(lambda a, uu: cyl_sdf(p[None, :], a, uu, rr)[0])(A, u)  # (nseg,)
        d_s = jnp.einsum('kj,kj->k', p[None, :] - A, n_start)   # <=0 inside start cut
        d_e = jnp.einsum('kj,kj->k', p[None, :] - B, n_end)     # <=0 inside end cut
        leg = jnp.maximum(jnp.maximum(d_cyl, d_s), d_e)         # exact mitred pipe (max)
        return jnp.min(leg)                                     # union of welded pipes
    return jax.vmap(one)(pts)


def _sdf_welded_helical(pts, params, sign, nfp, ntor, stellsym):
    """Signed distance from each point in ``pts`` to the welded-pipe vessel.

    Args:
        pts:      (M, 3) query points.
        params:   flat dof vector (nodes + rr, see _unpack).
        sign:     +1 outside-positive; -1 flips inside/outside.
        nfp,ntor: field-period / toroidal winding of the symmetry group.
        stellsym: whether the loop is stellarator symmetric (static flag).
    Returns:
        (M,) signed distances.
    """
    nodes, rr = _unpack(params)
    P = _all_joints(nodes, nfp, ntor, stellsym)
    A, B, u, n_start, n_end = _leg_geometry(P)
    return sign * _sdf_mitre(pts, A, B, u, n_start, n_end, rr)


def _geometric_penalty(params, nfp, ntor, stellsym):
    """Dimensionless validity penalty keeping the mitred tube an exact SDF:
      (1) radius positivity  rr > 0;
      (2) turn angle at each joint no sharper than MAX_TURN_DEG (cos of the angle
          between consecutive legs >= cos(MAX_TURN_DEG)), so the bisector stays
          well away from the degenerate 180 deg reversal;
      (3) mitre non-interference: each leg must be longer than the two mitre
          recessions rr*tan(theta/2) eating into it from its end joints, so the
          start/end cut planes never cross over the cylinder.
    Each term is a mean of squared hinges (smooth) and they add up."""
    nodes, rr = _unpack(params)
    P = _all_joints(nodes, nfp, ntor, stellsym)
    A = P
    B = jnp.roll(P, -1, axis=0)
    leg = B - A
    leg_len = jnp.linalg.norm(leg, axis=-1)
    u = leg / jnp.maximum(leg_len[:, None], 1e-30)
    uprev = jnp.roll(u, 1, axis=0)
    cos_turn = jnp.sum(uprev * u, axis=-1)          # angle between leg k-1 and leg k, at joint k

    pos = jnp.maximum(-rr, 0.0) ** 2
    sharp = jnp.mean(jnp.maximum(_COS_MIN_TURN - cos_turn, 0.0) ** 2)   # keep turns <= MAX_TURN_DEG
    cos_safe = jnp.clip(cos_turn, _COS_MIN_TURN, 1.0)
    t_half = jnp.sqrt(jnp.maximum(1.0 - cos_safe, 0.0) / (1.0 + cos_safe))   # tan(theta/2)
    reach = rr * t_half                                        # mitre recession at each joint
    reach_sum = reach + jnp.roll(reach, -1, axis=0)            # per leg: start joint + end joint
    scale = jnp.mean(leg_len) ** 2 + 1e-30
    interfere = jnp.mean(jnp.maximum(reach_sum - leg_len, 0.0) ** 2) / scale
    return pos + sharp + interfere


def quadratic_threshold_welded_helical(pts, params, sign, threshold, nfp, ntor, stellsym):
    sls = _sdf_welded_helical(pts, params, sign, nfp, ntor, stellsym)
    reach = _geometric_penalty(params, nfp, ntor, stellsym)
    return jnp.mean(jnp.maximum(threshold - sls, 0) ** 2) + reach


def quadratic_distance_welded_helical(pts, params, sign, threshold, nfp, ntor, stellsym):
    sls = _sdf_welded_helical(pts, params, sign, nfp, ntor, stellsym)
    dvalue = jnp.abs(sls - jnp.mean(sls))
    return jnp.mean(jnp.maximum(dvalue - threshold, 0) ** 2)


class HelicalCylinderVesselSDF(Optimizable):
    """Closed loop of ``nseg`` straight PIPES (constant radius rr) cut on an
    angle and welded at the joints -- a faceted helical vessel and an exact SDF.

    Unlike the harmonic HelicalVesselSDF, the DESIGN VARIABLES are the discrete
    xyz positions of the piecewise-linear centreline's nodes (plus the free
    radius rr). The loop is nfp-fold rotationally symmetric (optionally
    stellarator symmetric); only the fundamental-domain nodes are free dofs and
    the rest of the loop is generated by the symmetry group.

    Args:
        nseg:     total number of centreline legs in the closed loop. Must be
                  divisible by nfp (by 2*nfp when stellsym). May be omitted if
                  ``nodes`` is given (it is then derived).
        rr:       constant pipe radius (a FREE dof, seeded to this value).
        nfp:      field-period number of the symmetry group (default 1, or the
                  curve's nfp when ``curve`` is given).
        ntor:     toroidal winding number (default 1, or the curve's ntor).
        stellsym: stellarator symmetry (default True, or the curve's flag when
                  ``curve`` is given).
        nodes:    optional (n_free, 3) fundamental-domain node positions. If
                  omitted a planar circle of the right node count is seeded.
        curve:    optional simsopt curve (e.g. CurveXYZFourierSymmetries) whose
                  geometry seeds the nodes; it is sampled at the fundamental-
                  domain parameters and NOT retained (so the optimised node
                  state, not the seed curve, is what serialises).
    """
    def __init__(self, nseg=None, rr=0.2, nfp=None, ntor=None, stellsym=None,
                 nodes=None, curve=None, **kwargs):
        # Fill nfp/ntor/stellsym from the seed curve when left unspecified, else
        # default to a single non-winding stellsym loop.
        if curve is not None:
            if nfp is None:
                nfp = curve.nfp
            if ntor is None:
                ntor = getattr(curve, 'ntor', 1)
            if stellsym is None:
                stellsym = curve.stellsym
        self.nfp = 1 if nfp is None else int(nfp)
        self.ntor = 1 if ntor is None else int(ntor)
        self.stellsym = True if stellsym is None else bool(stellsym)
        per = (2 * self.nfp) if self.stellsym else self.nfp

        # Resolve the fundamental-domain nodes.
        if curve is not None:
            if nseg is None:
                raise ValueError("nseg is required when seeding from a curve")
            nodes = self._sample_curve(curve, int(nseg), self.nfp, self.stellsym)
        elif nodes is not None:
            nodes = np.asarray(nodes, float).reshape(-1, 3)
        else:
            if nseg is None:
                raise ValueError("provide either nseg (with/without curve) or nodes")
            if int(nseg) % per:
                raise ValueError(f"nseg={nseg} must be divisible by {per} "
                                 f"(nfp={self.nfp}, stellsym={self.stellsym})")
            n_free = int(nseg) // per
            t = (np.arange(n_free) + 0.5) / int(nseg)
            ang = 2.0 * np.pi * self.ntor * t
            nodes = np.stack([np.cos(ang), np.sin(ang), np.zeros(n_free)], axis=-1)

        n_free = len(nodes)
        resolved_nseg = per * n_free
        if nseg is not None and int(nseg) != resolved_nseg:
            raise ValueError(f"nseg={nseg} is inconsistent with {n_free} free nodes "
                             f"and the symmetry (expected {resolved_nseg})")
        self.nseg = resolved_nseg
        self.curve = None   # seed curve is not part of the (optimised) state

        x0 = np.concatenate([nodes.flatten(), [float(rr)]])
        names = [f'n{j}{c}' for j in range(n_free) for c in ('x', 'y', 'z')] + ['rr']
        super().__init__(depends_on=[], x0=x0, names=names, **kwargs)
        if not self.stellsym:
            # Rigid vertical (z) translation of the whole loop is a gauge freedom
            # here: the geometric penalty is translation-invariant, the distance
            # penalty is one-sided, and z-translation commutes with the nfp rotation
            # about z, so it moves the loop rigidly with no change to any penalty.
            # Pin one node's z (as HelicalVesselSDF pins zc(0)). For stellsym the
            # z -> -z reflection already fixes the z=0 plane, so nothing is pinned.
            self.fix('n0z')

        _sj = dict(nfp=self.nfp, ntor=self.ntor, stellsym=self.stellsym)
        # JIT the closed-form SDF (static symmetry args bound; only pts/params/sign vary).
        self.pure = jax.jit(partial(_sdf_welded_helical, **_sj))
        self.quadratic_threshold = partial(quadratic_threshold_welded_helical, **_sj)
        self.quadratic_distance = partial(quadratic_distance_welded_helical, **_sj)

    @staticmethod
    def _sample_curve(curve, nseg, nfp, stellsym):
        """Sample ``curve`` at the fundamental-domain cell centres to seed the
        free nodes (n_free, 3). A same-type curve is rebuilt at those quadpoints
        and given the original dofs, so the sampling is exact for any simsopt
        curve carrying (order, nfp, stellsym[, ntor])."""
        per = (2 * nfp) if stellsym else nfp
        if int(nseg) % per:
            raise ValueError(f"nseg={nseg} must be divisible by {per} "
                             f"(nfp={nfp}, stellsym={stellsym})")
        n_free = int(nseg) // per
        t = (np.arange(n_free) + 0.5) / int(nseg)
        c2 = curve.__class__(list(t), curve.order, curve.nfp, curve.stellsym,
                             ntor=getattr(curve, 'ntor', 1))
        c2.x = curve.x
        return np.asarray(c2.gamma())

    @classmethod
    def from_curve_xyz_fourier_symmetries(cls, curve, rr, nseg, stellsym=None, **kwargs):
        """Build from a simsopt CurveXYZFourierSymmetries, seeding the ``nseg``
        centreline nodes by sampling the curve and copying its nfp/ntor/stellsym.
        Mirrors HelicalVesselSDF.from_curve_xyz_fourier_symmetries."""
        return cls(nseg=nseg, rr=rr, nfp=curve.nfp, ntor=getattr(curve, 'ntor', 1),
                   stellsym=(curve.stellsym if stellsym is None else stellsym),
                   curve=curve, **kwargs)

    # --- live views off the current dof vector, matching the __init__ arg names
    # so the default simsopt GSON serialisation reconstructs via __init__. ---
    @property
    def n_free(self):
        return (len(self.local_full_x) - 1) // 3

    @property
    def nodes(self):
        x = self.local_full_x
        return [[float(v) for v in x[3 * j:3 * j + 3]] for j in range(self.n_free)]

    @property
    def rr(self):
        return float(self.local_full_x[-1])

    def num_dofs(self):
        return len(self.local_full_x)

    def joints(self):
        """The full ordered loop of ``nseg`` weld joints as an (nseg, 3) array."""
        nodes, _rr = _unpack(self.local_full_x)
        return np.asarray(_all_joints(nodes, self.nfp, self.ntor, self.stellsym))

    def max_turn_angle(self):
        """Largest turn angle (deg) between consecutive legs; the mitre stays
        exact well below 180 deg (the geometric penalty keeps it <= MAX_TURN_DEG)."""
        P = self.joints()
        u = P[np.arange(1, len(P) + 1) % len(P)] - P
        u = u / np.linalg.norm(u, axis=-1, keepdims=True)
        cos_turn = np.sum(np.roll(u, 1, axis=0) * u, axis=-1)
        return float(np.degrees(np.arccos(np.clip(cos_turn, -1.0, 1.0))).max())

    def geometric_violation(self):
        """Worst geometric-validity violation of the mitred tube as a single
        non-negative scalar comparable to the 0.1% design gate (0 == valid).
        Mirrors _geometric_penalty's three conditions but as a max of relative
        excesses (like the other SDFs' vessel_shape_err): rr > 0, turns no
        sharper than MAX_TURN_DEG, and every leg longer than the two mitre
        recessions rr*tan(theta/2) eating in from its end joints."""
        P = self.joints()
        rr = self.rr
        leg = np.roll(P, -1, axis=0) - P
        leg_len = np.linalg.norm(leg, axis=-1)
        u = leg / np.maximum(leg_len[:, None], 1e-30)
        cos_turn = np.clip(np.sum(np.roll(u, 1, axis=0) * u, axis=-1), -1.0, 1.0)
        turn_vio = max((np.degrees(np.arccos(cos_turn)).max() - MAX_TURN_DEG) / MAX_TURN_DEG, 0.0)
        cos_safe = np.clip(cos_turn, _COS_MIN_TURN, 1.0)
        reach = rr * np.sqrt(np.maximum(1.0 - cos_safe, 0.0) / (1.0 + cos_safe))  # rr*tan(theta/2)
        reach_sum = reach + np.roll(reach, -1)                                    # per leg: both joints
        mitre_vio = float(np.max(np.maximum(reach_sum / np.maximum(leg_len, 1e-30) - 1.0, 0.0)))
        return float(max(turn_vio, mitre_vio, max(-rr, 0.0)))

    def eval(self, x, y, z):
        pts = np.concatenate((x.flatten()[:, None], y.flatten()[:, None],
                              z.flatten()[:, None]), axis=-1)
        return np.array(self.pure(pts, self.local_full_x, 1.0).astype(np.float32).reshape(x.shape))

    def rz_bounds(self):
        """Conservative (R_max, |Z|_max): the largest cylindrical radius and
        height over the joints, plus the pipe radius rr."""
        P = self.joints()
        rr = self.rr
        R_max = float(np.hypot(P[:, 0], P[:, 1]).max() + abs(rr))
        Z_max = float(np.abs(P[:, 2]).max() + abs(rr))
        return R_max, Z_max

    def to_vtk(self, name, nx=60, ny=60, nz=40):
        R_max, Z_max = self.rz_bounds(); pad = 0.1
        xs = np.linspace(-(R_max + pad), R_max + pad, nx).astype(np.float32)
        ys = np.linspace(-(R_max + pad), R_max + pad, ny).astype(np.float32)
        zs = np.linspace(-(Z_max + pad), Z_max + pad, nz).astype(np.float32)
        X, Y, Z = np.meshgrid(xs, ys, zs, indexing="ij")
        pts = np.concatenate((X.flatten()[:, None], Y.flatten()[:, None],
                              Z.flatten()[:, None]), axis=-1)
        D = np.array(self.pure(pts, self.local_full_x, 1.0).astype(np.float32).reshape((nx, ny, nz)))
        gridToVTK(name, x=xs, y=ys, z=zs, cellData=None, pointData={"sdf": D})
