from functools import partial
import numpy as np
import jax
import jax.numpy as jnp
from simsopt._core import Optimizable
from pyevtk.hl import gridToVTK  # pip install pyevtk

# ---------------------------------------------------------------------------
# Welded-pipe helical vessel SDF. The dofs are the DISCRETE xyz node positions of
# a piecewise-linear (polyline) centreline (NOT Fourier harmonics) plus the
# constant pipe radius rr. Like the other SDFs here it exposes self.pure /
# quadratic_threshold / quadratic_distance / eval / rz_bounds / to_vtk, so it is
# a drop-in vessel for VesselDistance and round-trips through the design JSONs.
#
# CENTRELINE (closed loop of ``nseg`` legs): nfp-fold rotationally and optionally
# stellarator symmetric. Only the fundamental-domain nodes are free; the rest is
# generated by the symmetry group: rotation Q=Rot_z(2*pi*ntor/nfp) between field
# periods, and reflection R=Q*diag(1,-1,-1) folding a period in half. Free nodes
# sit at cell centres so none lands on a symmetry plane. `num_nodes` is the free
# node count per HALF field period (stellsym) or FULL period (else):
#     stellsym=True:   nseg = 2*nfp*num_nodes
#     stellsym=False:  nseg =   nfp*num_nodes
# With `boundary_node` (stellsym only) node 0 sits ON the t=0 plane (x-axis,
# y=z=0 pinned), emitted once without a mirror, giving an ODD leg count
#     nseg = nfp*(2*(num_nodes-1)+1)   e.g. nfp=2, num_nodes=2 -> nseg=6.
#
# TUBE (exact Euclidean SDF): leg k is the radius-rr cylinder about P_k->P_{k+1}
# clipped by the bisector planes at its endpoints. Per query point/leg, project
# onto the unrestricted cylinder; if the projection lies between the mitre planes
# the radial distance is exact, else the closest point is on one of the two
# elliptical mitre rings (fixed-count point-to-ellipse solve). The min unsigned
# distance over exposed patches is signed by membership in the union of clipped
# solid cylinders (shared mitre disks are internal). Exact when legs are nonzero,
# no 180-deg reversal, mitre cuts do not overlap, and nonadjacent pieces do not
# intersect; _geometric_penalty enforces the local conditions.
#
# DOF LAYOUT: params = concat([node_0(xyz), ..., node_{n_free-1}(xyz), rr]).
# ---------------------------------------------------------------------------


# Turn-angle cap for the mitre welds: beyond this the weld nears the 180-deg
# reversal where the bisector is ill-defined. 150 deg leaves a right-angle
# quadrilateral (nseg=4) comfortable; the mitre term does the finer work.
MAX_TURN_DEG = 150.0
_COS_MIN_TURN = float(np.cos(np.radians(MAX_TURN_DEG)))   # cos(150 deg) ~ -0.866
_MITER_ELLIPSE_BISECTION_ITERS = 48
_MIN_RELATIVE_GEOMETRY_SIZE = 1e-7


def _rot_z(theta):
    """3x3 rotation about the z-axis by angle ``theta`` (jax array)."""
    c, s = jnp.cos(theta), jnp.sin(theta)
    return jnp.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


def _unpack(params):
    """Split the flat dof vector into the fundamental-domain nodes (n_free, 3)
    and the constant pipe radius rr. n_free = (len(params)-1)//3."""
    n_free = (params.shape[0] - 1) // 3
    nodes = params[:3 * n_free].reshape(n_free, 3)
    rr = params[3 * n_free]
    return nodes, rr


def _nseg(nfp, stellsym, boundary_node, n_free):
    """Total legs/joints in the closed loop. Count the joints in one field
    period, then multiply by nfp:
        non-stellsym            : n_free nodes                  -> nfp*n_free
        stellsym                : n_free nodes + n_free refl.    -> 2*nfp*n_free
        stellsym, boundary_node : boundary node + n_interior     -> nfp*(2*n_interior+1)
                                  interior + n_interior refl.
    with n_interior = n_free - 1 (node 0 is the boundary node), giving an ODD
    count per period so nseg need not be a multiple of 2*nfp.
    """
    if stellsym:
        if boundary_node:
            n_interior = n_free - 1            # every node except the boundary node
            return nfp * (2 * n_interior + 1)
        return 2 * nfp * n_free
    return nfp * n_free


def _all_joints(nodes, nfp, ntor, stellsym, boundary_node=False):
    """Full ordered list of ``nseg`` centreline joints (nseg, 3) from the
    fundamental-domain ``nodes``, applying the symmetry group by increasing t:
    the free nodes, then their reflection R=Q*S (reversed), then the nfp rotations
    Q^m tiling the field periods. With ``boundary_node`` (stellsym only) nodes[0]
    sits ON the t=0 plane (y=z=0), emitted ONCE and not reflected, so the period
    has an ODD leg count."""
    alpha = 2.0 * jnp.pi * ntor / nfp
    Q = _rot_z(alpha)
    if stellsym:
        S = jnp.diag(jnp.array([1.0, -1.0, -1.0]))
        R = Q @ S                              # reflection isometry, t -> 1/nfp - t
        if boundary_node:
            b = nodes[:1]                      # node on the t=0 plane (not reflected)
            interior = nodes[1:]
            refl = (R @ interior.T).T          # images of the interior nodes
            half = jnp.concatenate([b, interior, refl[::-1]], axis=0)   # one field period
        else:
            refl = (R @ nodes.T).T             # images of the free nodes
            half = jnp.concatenate([nodes, refl[::-1]], axis=0)   # one full field period
    else:
        half = nodes                           # one full field period
    blocks = [(_rot_z(m * alpha) @ half.T).T for m in range(nfp)]
    return jnp.concatenate(blocks, axis=0)


def _fundamental_t(n_free, nfp, stellsym, boundary_node):
    """Curve parameters t in [0, 1/nfp) of the ``n_free`` fundamental-domain nodes.
    All joints are uniformly spaced at k/nseg; the free nodes sit at cell centres
    (offset 0.5, off both stellarator planes) unless a boundary node anchors node 0
    ON the t=0 plane (offset 0), with nodes 1.. the interior nodes."""
    nseg = _nseg(nfp, stellsym, boundary_node, n_free)
    offset = 0.0 if (stellsym and boundary_node) else 0.5
    return (np.arange(n_free) + offset) / nseg


def _miter_dot(a, b):
    """Dot product over the Cartesian axis with leading-axis broadcasting."""
    return jnp.sum(a * b, axis=-1)


@jax.custom_jvp
def _miter_safe_norm(x):
    """Euclidean norm with the zero vector assigned a zero subgradient."""
    return jnp.sqrt(jnp.sum(x * x, axis=-1))


@_miter_safe_norm.defjvp
def _miter_safe_norm_jvp(primals, tangents):
    (x,), (dx,) = primals, tangents
    norm = _miter_safe_norm(x)
    safe_norm = jnp.where(norm > 0.0, norm, 1.0)
    dnorm = jnp.where(
        norm > 0.0,
        jnp.sum(x * dx, axis=-1) / safe_norm,
        0.0,
    )
    return norm, dnorm


def _safe_normalize(v, fallback):
    """Normalize vectors along the last axis, using ``fallback`` at zero."""
    n = _miter_safe_norm(v)[..., None]
    safe = jnp.where(n > 0.0, n, 1.0)
    return jnp.where(n > 0.0, v / safe, fallback)


def _leg_geometry_full(P):
    """Return starts, ends, lengths, tangents, and start mitre normals."""
    A = P
    B = jnp.roll(P, -1, axis=0)
    edges = B - A
    lengths = _miter_safe_norm(edges)
    u = _safe_normalize(edges, jnp.array([1.0, 0.0, 0.0], dtype=P.dtype))
    uprev = jnp.roll(u, 1, axis=0)
    n_bis = _safe_normalize(uprev + u, u)
    return A, B, lengths, u, n_bis


def _leg_geometry(P):
    """Compatibility helper returning ``(A, u, n_bis)`` as before."""
    A, _B, _lengths, u, n_bis = _leg_geometry_full(P)
    return A, u, n_bis


def _miter_ellipse_closest_point(p, semimajor, semiminor):
    """Closest point on x^2/a^2 + y^2/b^2 = 1 for a >= b > 0.

    The strictly monotone Lagrange-multiplier equation is solved by a fixed
    number of bisection iterations, making the routine JIT compatible.
    """
    p = jnp.asarray(p)
    a = jnp.asarray(semimajor, dtype=p.dtype)
    b = jnp.asarray(semiminor, dtype=p.dtype)

    x = jnp.abs(p[..., 0])
    y = jnp.abs(p[..., 1])
    a, b, x, y = jnp.broadcast_arrays(a, b, x, y)

    finfo = jnp.finfo(p.dtype)
    eps = finfo.eps

    # Exact coordinate-axis cases are handled below. These floors protect only
    # the generic branch, which JAX may still evaluate under vectorization.
    x_safe = jnp.where(x > 0.0, x, jnp.maximum(eps * a, finfo.tiny))
    y_safe = jnp.where(y > 0.0, y, jnp.maximum(eps * b, finfo.tiny))

    ratio2 = jnp.square(a / b)
    z0 = x_safe / a
    z1 = y_safe / b
    n0 = ratio2 * z0
    g0 = jnp.square(z0) + jnp.square(z1) - 1.0

    # Root bracket for s = lambda / b^2.
    lo = jnp.where(g0 < 0.0, z1 - 1.0, 0.0)
    hi = jnp.where(g0 < 0.0, 0.0, jnp.hypot(n0, z1) - 1.0)

    def bisect_body(_, state):
        lo_i, hi_i = state
        s = 0.5 * (lo_i + hi_i)
        q0 = n0 / (s + ratio2)
        q1 = z1 / (s + 1.0)
        residual = q0 * q0 + q1 * q1 - 1.0
        return (
            jnp.where(residual > 0.0, s, lo_i),
            jnp.where(residual > 0.0, hi_i, s),
        )

    lo, hi = jax.lax.fori_loop(
        0,
        _MITER_ELLIPSE_BISECTION_ITERS,
        bisect_body,
        (lo, hi),
    )
    s = 0.5 * (lo + hi)
    q_general = jnp.stack(
        (
            ratio2 * x_safe / (s + ratio2),
            y_safe / (s + 1.0),
        ),
        axis=-1,
    )

    # y == 0 can have an off-axis closest point inside the ellipse evolute.
    denominator = jnp.square(a) - jnp.square(b)
    denominator_safe = jnp.where(denominator > 0.0, denominator, 1.0)
    u = jnp.clip(a * x / denominator_safe, 0.0, 1.0)
    q_xaxis_off = jnp.stack(
        (
            a * u,
            b * jnp.sqrt(jnp.maximum(0.0, 1.0 - u * u)),
        ),
        axis=-1,
    )
    q_xaxis_end = jnp.stack((a, jnp.zeros_like(a)), axis=-1)
    q_xaxis = jnp.where(
        (a * x < denominator)[..., None],
        q_xaxis_off,
        q_xaxis_end,
    )

    # x == 0 has closest representative (0, b).
    q_yaxis = jnp.stack((jnp.zeros_like(b), b), axis=-1)
    q_ellipse = jnp.where(
        (x == 0.0)[..., None],
        q_yaxis,
        jnp.where((y == 0.0)[..., None], q_xaxis, q_general),
    )

    # Stable limit for a circular section (straight joint).
    circle_tolerance = 8.0 * eps * jnp.maximum(a, b)
    is_circle = jnp.abs(a - b) <= circle_tolerance
    p_radius = jnp.hypot(x, y)
    p_radius_safe = jnp.where(p_radius > 0.0, p_radius, 1.0)
    q_circle_radial = (
        a[..., None]
        * jnp.stack((x, y), axis=-1)
        / p_radius_safe[..., None]
    )
    q_circle_center = jnp.stack((a, jnp.zeros_like(a)), axis=-1)
    q_circle = jnp.where(
        (p_radius > 0.0)[..., None],
        q_circle_radial,
        q_circle_center,
    )
    q_abs = jnp.where(is_circle[..., None], q_circle, q_ellipse)

    signs = jnp.stack(
        (
            jnp.where(p[..., 0] < 0.0, -1.0, 1.0),
            jnp.where(p[..., 1] < 0.0, -1.0, 1.0),
        ),
        axis=-1,
    )
    return q_abs * signs


@jax.custom_jvp
def _miter_ellipse_curve_distance(p, semimajor, semiminor):
    """Unsigned Euclidean distance from 2-D points to an ellipse curve."""
    closest = _miter_ellipse_closest_point(p, semimajor, semiminor)
    return _miter_safe_norm(p - closest)


@_miter_ellipse_curve_distance.defjvp
def _miter_ellipse_curve_distance_jvp(primals, tangents):
    # The envelope theorem supplies the derivative without differentiating the
    # discrete bisection decisions.
    p, a, b = primals
    dp, da, db = tangents

    closest = _miter_ellipse_closest_point(p, a, b)
    delta = p - closest
    distance = _miter_safe_norm(delta)
    safe_distance = jnp.where(distance > 0.0, distance, 1.0)
    normal = jnp.where(
        (distance > 0.0)[..., None],
        delta / safe_distance[..., None],
        0.0,
    )

    derivative = (
        _miter_dot(normal, dp)
        - normal[..., 0] * closest[..., 0] / a * da
        - normal[..., 1] * closest[..., 1] / b * db
    )
    return distance, derivative


def _miter_ring_distance(points, vertex, tangent, miter_normal, radius):
    """Exact Euclidean distance to one elliptical mitre ring."""
    offset = points - vertex
    eps = jnp.finfo(offset.dtype).eps

    cosine = jnp.clip(_miter_dot(tangent, miter_normal), eps, 1.0)
    height = _miter_dot(offset, miter_normal)
    sine2 = jnp.maximum(0.0, 1.0 - cosine * cosine)

    major_axis = (
        tangent - cosine[..., None] * miter_normal
    ) / jnp.sqrt(jnp.maximum(sine2, eps))[..., None]
    minor_axis = jnp.cross(miter_normal, major_axis)

    coordinates = jnp.stack(
        (
            _miter_dot(offset, major_axis),
            _miter_dot(offset, minor_axis),
        ),
        axis=-1,
    )
    semimajor = radius / cosine
    in_plane_distance = _miter_ellipse_curve_distance(
        coordinates,
        semimajor,
        radius,
    )
    ellipse_distance = jnp.hypot(height, in_plane_distance)

    # A straight joint has a circular ring in a plane normal to the tangent.
    planar = offset - height[..., None] * miter_normal
    circle_distance = jnp.hypot(
        height,
        _miter_safe_norm(planar) - radius,
    )
    return jnp.where(
        sine2 <= 16.0 * eps,
        circle_distance,
        ellipse_distance,
    )


def _sdf_exact_miter_pipe(pts, A, lengths, u, n_bis, rr):
    """Exact SDF of the valid closed polyline pipe described by leg geometry.

    The unsigned distance is the minimum distance to the exposed cylindrical
    side patches. Internal mitre disks are used only for the global membership
    test and are never included as boundary-distance candidates.
    """
    points = jnp.asarray(pts)
    if points.ndim < 1 or points.shape[-1] != 3:
        raise ValueError("pts must have shape (..., 3)")

    output_shape = points.shape[:-1]
    points = points.reshape((-1, 3))

    B = jnp.roll(A, -1, axis=0)
    p = points[:, None, :]
    a = A[None, :, :]
    b = B[None, :, :]
    tangent = u[None, :, :]
    start_miter = n_bis[None, :, :]
    end_miter = jnp.roll(n_bis, -1, axis=0)[None, :, :]
    segment_length = lengths[None, :]

    relative = p - a
    axial = _miter_dot(relative, tangent)
    radial = relative - axial[..., None] * tangent
    radial_length = _miter_safe_norm(radial)
    radial_nonzero = radial_length > 0.0
    safe_radial_length = jnp.where(radial_nonzero, radial_length, 1.0)

    # Closest point on each unrestricted infinite cylindrical side surface.
    cylinder_point = (
        a
        + axial[..., None] * tangent
        + rr * radial / safe_radial_length[..., None]
    )
    projection_on_patch = (
        radial_nonzero
        & (_miter_dot(cylinder_point - a, start_miter) >= 0.0)
        & (_miter_dot(cylinder_point - b, end_miter) <= 0.0)
    )
    unrestricted_cylinder_distance = jnp.abs(radial_length - rr)

    # If the unrestricted projection is not on the clipped patch, the
    # constrained closest point lies on one of the two elliptical edge rings.
    ring_at_vertex = _miter_ring_distance(
        p,
        a,
        tangent,
        start_miter,
        rr,
    )
    ring_distance = jnp.minimum(
        ring_at_vertex,
        jnp.roll(ring_at_vertex, -1, axis=1),
    )

    # On the axis, the unrestricted cylindrical projection is non-unique. For
    # an interference-free segment, an admissible side point is exactly rr away
    # between its centerline endpoints. Outside that interval, the ring fallback
    # gives the same result wherever an overhanging mitre section is admissible.
    axis_has_side_patch = (
        (~radial_nonzero)
        & (axial >= 0.0)
        & (axial <= segment_length)
    )
    patch_distance = jnp.where(
        projection_on_patch,
        unrestricted_cylinder_distance,
        jnp.where(axis_has_side_patch, rr, ring_distance),
    )

    # Membership in the union of clipped solid cylinders supplies one global
    # sign. Shared mitre disks are internal to this union and therefore do not
    # participate in the unsigned boundary distance above.
    inside_piece = (
        (_miter_dot(radial, radial) <= rr * rr)
        & (_miter_dot(p - a, start_miter) >= 0.0)
        & (_miter_dot(p - b, end_miter) <= 0.0)
    )

    unsigned_distance = jnp.min(patch_distance, axis=1)
    signed_distance = jnp.where(
        jnp.any(inside_piece, axis=1),
        -unsigned_distance,
        unsigned_distance,
    )
    return signed_distance.reshape(output_shape)


def _sdf_split(pts, A, u, n_bis, rr):
    """Compatibility wrapper for the old private helper; now evaluates exactly."""
    lengths = _miter_safe_norm(jnp.roll(A, -1, axis=0) - A)
    return _sdf_exact_miter_pipe(pts, A, lengths, u, n_bis, rr)


def _sdf_welded_helical(pts, params, sign, nfp, ntor, stellsym, boundary_node=False):
    """Exact signed distance to a valid welded, mitred polyline pipe.

    Exactness requires positive radius, nonzero legs, no 180-degree reversal,
    nonoverlapping mitre cuts on each leg, and no overlap between nonadjacent
    pipe pieces. ``_geometric_penalty`` enforces the local conditions; global
    self-intersection must be excluded by the surrounding design constraints.
    """
    points = jnp.asarray(pts)
    dtype = jnp.result_type(points, jnp.asarray(params), jnp.float32)
    points = points.astype(dtype)
    params = jnp.asarray(params, dtype=dtype)

    nodes, rr_raw = _unpack(params)
    P = _all_joints(nodes, nfp, ntor, stellsym, boundary_node)
    A, _B, lengths, u, n_bis = _leg_geometry_full(P)

    # Keep invalid optimization iterates finite. In the valid domain this is
    # exactly rr_raw; the geometry penalty supplies the restoring gradient when
    # rr_raw is nonpositive.
    scale = jnp.maximum(1.0, jnp.max(lengths))
    radius_floor = jnp.finfo(dtype).eps * scale
    rr = jnp.maximum(rr_raw, radius_floor)

    sdf = _sdf_exact_miter_pipe(points, A, lengths, u, n_bis, rr)
    return jnp.asarray(sign, dtype=dtype) * sdf


def _validity_components(params, nfp, ntor, stellsym, boundary_node=False):
    """Local geometry arrays used by the exactness penalty and diagnostics.

    The returned mitre clearance for leg i is

        length[i] - start_setback[i] - end_setback[i].

    Positive clearance means the two cuts do not overlap on that leg. Global
    intersections between nonadjacent pipe pieces are intentionally not replaced
    by a conservative capsule test, since that test rejects valid finely sampled
    centerlines.
    """
    nodes, rr = _unpack(params)
    P = _all_joints(nodes, nfp, ntor, stellsym, boundary_node)
    _A, _B, lengths, u, n_bis = _leg_geometry_full(P)

    scale = jnp.maximum(
        1.0,
        jnp.maximum(jnp.max(lengths), jnp.abs(rr)),
    )
    radius = jnp.maximum(rr, 0.0)

    cos_turn = jnp.clip(
        _miter_dot(jnp.roll(u, 1, axis=0), u),
        -1.0,
        1.0,
    )

    start_cos = jnp.clip(_miter_dot(u, n_bis), 0.0, 1.0)
    end_cos = jnp.clip(
        _miter_dot(u, jnp.roll(n_bis, -1, axis=0)),
        0.0,
        1.0,
    )
    cosine_floor = jnp.sqrt(jnp.finfo(P.dtype).eps)
    start_cos_safe = jnp.maximum(start_cos, cosine_floor)
    end_cos_safe = jnp.maximum(end_cos, cosine_floor)

    start_setback = (
        radius
        * jnp.sqrt(jnp.maximum(0.0, 1.0 - start_cos * start_cos))
        / start_cos_safe
    )
    end_setback = (
        radius
        * jnp.sqrt(jnp.maximum(0.0, 1.0 - end_cos * end_cos))
        / end_cos_safe
    )
    miter_clearance = lengths - start_setback - end_setback

    return rr, scale, lengths, cos_turn, miter_clearance


def _geometric_penalty(params, nfp, ntor, stellsym, boundary_node=False):
    """Dimensionless LOCAL validity penalty for the exact SDF.

    It penalizes nonpositive radius, degenerate legs, near-reversal turns, and
    overlapping mitre cuts. Exactness also requires that nonadjacent pipe pieces
    do not intersect; that global condition must be enforced by the surrounding
    design constraints or checked separately for the intended geometry.
    """
    rr, scale, lengths, cos_turn, miter_clearance = _validity_components(
        params, nfp, ntor, stellsym, boundary_node
    )

    min_size = _MIN_RELATIVE_GEOMETRY_SIZE * scale
    radius_term = jnp.square(jnp.maximum((min_size - rr) / scale, 0.0))
    edge_term = jnp.mean(
        jnp.square(jnp.maximum((min_size - lengths) / scale, 0.0))
    )
    turn_term = jnp.mean(
        jnp.square(jnp.maximum(_COS_MIN_TURN - cos_turn, 0.0))
    )
    miter_term = jnp.mean(
        jnp.square(jnp.maximum(-miter_clearance / scale, 0.0))
    )
    return radius_term + edge_term + turn_term + miter_term


def quadratic_threshold_welded_helical(pts, params, sign, threshold, nfp, ntor, stellsym,
                                       boundary_node=False):
    sls = _sdf_welded_helical(pts, params, sign, nfp, ntor, stellsym, boundary_node)
    reach = _geometric_penalty(params, nfp, ntor, stellsym, boundary_node)
    return jnp.mean(jnp.maximum(threshold - sls, 0) ** 2) + reach


def quadratic_distance_welded_helical(pts, params, sign, threshold, nfp, ntor, stellsym,
                                      boundary_node=False):
    sls = _sdf_welded_helical(pts, params, sign, nfp, ntor, stellsym, boundary_node)
    dvalue = jnp.abs(sls - jnp.mean(sls))
    return jnp.mean(jnp.maximum(dvalue - threshold, 0) ** 2)


class HelicalCylinderVesselSDF(Optimizable):
    """Closed loop of straight circular pipes joined by exact mitre cuts.

    The SDF is the exact Euclidean signed distance when the local conditions
    reported by :meth:`geometric_violation` hold and nonadjacent pipe pieces do
    not intersect.

    Unlike the harmonic HelicalVesselSDF, the DESIGN VARIABLES are the discrete
    xyz positions of the piecewise-linear centreline's nodes (plus the free
    radius rr). The loop is nfp-fold rotationally symmetric (optionally
    stellarator symmetric); only the fundamental-domain nodes are free dofs and
    the rest of the loop is generated by the symmetry group.

    Args:
        num_nodes: free node count in the fundamental domain (per HALF field
                  period when stellsym, else per FULL period; the boundary node,
                  if any, is node 0 and is counted). Derived if ``nodes`` given.
        rr:       constant pipe radius (a FREE dof, seeded to this value).
        nfp, ntor, stellsym: symmetry group (default 1, 1, True, or taken from
                  ``curve`` when it is given).
        nodes:    (n_free, 3) fundamental-domain node positions. Provide these
                  or a seed ``curve``.
        curve:    optional simsopt curve sampled to seed the nodes; NOT retained
                  (the optimized nodes, not the curve, are what serialize).
        boundary_node: (stellsym only) put node 0 ON the t=0 plane (y=z=0,
                  pinned), emitted once and NOT mirrored, so nseg can be odd per
                  period, nseg = nfp*(2*(num_nodes-1)+1) (e.g. 6 legs at nfp=2).
    """
    def __init__(self, num_nodes=None, rr=0.2, nfp=None, ntor=None, stellsym=None,
                 nodes=None, curve=None, boundary_node=False, **kwargs):
        # Fill nfp/ntor/stellsym from the seed curve when left unspecified, else
        # default to a single non-winding stellsym loop.
        if curve is not None:
            if nfp is None:
                nfp = curve.nfp
            if ntor is None:
                ntor = getattr(curve, 'ntor', 1)
            if stellsym is None:
                stellsym = curve.stellsym
        self.nfp = 1 if nfp is None else int(nfp)
        self.ntor = 1 if ntor is None else int(ntor)
        self.stellsym = True if stellsym is None else bool(stellsym)
        # boundary_node (stellsym only): nodes[0] sits ON the t=0 plane, emitted
        # once without a mirror, so nseg can be odd per period. y,z pinned below.
        self.boundary_node = bool(boundary_node)
        if self.boundary_node and not self.stellsym:
            raise ValueError("boundary_node=True requires stellsym=True")

        # Resolve the fundamental-domain nodes: num_nodes is the free node count
        # n_free (boundary node included), and nseg follows from _nseg.
        if curve is not None:
            if num_nodes is None:
                raise ValueError("num_nodes is required when seeding from a curve")
            nodes = self._sample_curve(curve, int(num_nodes), self.nfp, self.stellsym,
                                       self.boundary_node)
        elif nodes is not None:
            nodes = np.asarray(nodes, float).reshape(-1, 3)
        else:
            raise ValueError("provide either explicit nodes or a seed curve")

        n_free = len(nodes)
        if num_nodes is not None and int(num_nodes) != n_free:
            raise ValueError(f"num_nodes={num_nodes} is inconsistent with the "
                             f"{n_free} nodes provided")
        if self.boundary_node:
            # Force node 0 onto the x-axis so pinning y,z below stays exactly stellsym.
            nodes[0, 1] = 0.0
            nodes[0, 2] = 0.0
        nseg = _nseg(self.nfp, self.stellsym, self.boundary_node, n_free)
        if nseg < 3:
            raise ValueError(
                "a closed mitred pipe requires at least three generated joints; "
                f"this configuration generates {nseg}"
            )
        self.curve = None   # seed curve is not part of the (optimised) state

        x0 = np.concatenate([nodes.flatten(), [float(rr)]])
        names = [f'n{j}{c}' for j in range(n_free) for c in ('x', 'y', 'z')] + ['rr']
        super().__init__(depends_on=[], x0=x0, names=names, **kwargs)
        if not self.stellsym:
            # Rigid z-translation of the loop is a gauge freedom (it changes no
            # penalty), so pin one node's z. Stellsym already fixes the z=0 plane.
            self.fix('n0z')
        elif self.boundary_node:
            # Keep the boundary node on the x-axis: x free, y,z pinned to stay stellsym.
            self.fix('n0y')
            self.fix('n0z')

        _sj = dict(nfp=self.nfp, ntor=self.ntor, stellsym=self.stellsym,
                   boundary_node=self.boundary_node)
        # JIT the exact SDF (static symmetry args bound; only pts/params/sign vary).
        self.pure = jax.jit(partial(_sdf_welded_helical, **_sj))
        self.quadratic_threshold = partial(quadratic_threshold_welded_helical, **_sj)
        self.quadratic_distance = partial(quadratic_distance_welded_helical, **_sj)

    @staticmethod
    def _sample_curve(curve, num_nodes, nfp, stellsym, boundary_node=False):
        """Sample ``curve`` at the fundamental-domain parameters to seed the
        ``num_nodes`` nodes (num_nodes, 3): a same-type curve is rebuilt at those
        quadpoints with the original dofs, so the sampling is exact. With a
        boundary node, node 0 is sampled at t=0 (on the x-axis)."""
        t = _fundamental_t(int(num_nodes), nfp, stellsym, boundary_node)
        c2 = curve.__class__(list(t), curve.order, curve.nfp, curve.stellsym,
                             ntor=getattr(curve, 'ntor', 1))
        c2.x = curve.x
        return np.asarray(c2.gamma())

    # --- live views off the current dof vector, matching the __init__ arg names
    # so the default simsopt GSON serialisation reconstructs via __init__. ---
    @property
    def n_free(self):
        return (len(self.local_full_x) - 1) // 3

    @property
    def num_nodes(self):
        # __init__ arg: free fundamental-domain node count (== n_free).
        return self.n_free

    @property
    def nodes(self):
        x = self.local_full_x
        return [[float(v) for v in x[3 * j:3 * j + 3]] for j in range(self.n_free)]

    @property
    def rr(self):
        return float(self.local_full_x[-1])

    def num_dofs(self):
        return len(self.local_full_x)

    def joints(self):
        """The full ordered loop of ``nseg`` weld joints as an (nseg, 3) array."""
        nodes, _rr = _unpack(self.local_full_x)
        return np.asarray(_all_joints(nodes, self.nfp, self.ntor, self.stellsym,
                                      self.boundary_node))

    def max_turn_angle(self):
        """Largest turn angle in degrees between consecutive centerline legs."""
        P = self.joints()
        edges = np.roll(P, -1, axis=0) - P
        lengths = np.linalg.norm(edges, axis=-1)
        u = edges / np.maximum(lengths[:, None], np.finfo(float).tiny)
        cos_turn = np.sum(np.roll(u, 1, axis=0) * u, axis=-1)
        return float(
            np.degrees(np.arccos(np.clip(cos_turn, -1.0, 1.0))).max()
        )

    def minimum_miter_clearance(self):
        """Minimum leg length minus its two axial mitre setbacks.

        A positive value means the start and end cuts do not overlap on any leg.
        This is a local condition and does not test nonadjacent self-intersection.
        """
        P = self.joints()
        radius = max(self.rr, 0.0)
        edges = np.roll(P, -1, axis=0) - P
        lengths = np.linalg.norm(edges, axis=-1)
        u = edges / np.maximum(lengths[:, None], np.finfo(float).tiny)

        sums = np.roll(u, 1, axis=0) + u
        miters = sums / np.maximum(
            np.linalg.norm(sums, axis=-1, keepdims=True),
            np.finfo(float).tiny,
        )

        c_start = np.clip(
            np.sum(u * miters, axis=-1),
            np.finfo(float).eps,
            1.0,
        )
        c_end = np.clip(
            np.sum(u * np.roll(miters, -1, axis=0), axis=-1),
            np.finfo(float).eps,
            1.0,
        )
        start_setback = (
            radius * np.sqrt(np.maximum(0.0, 1.0 - c_start * c_start))
            / c_start
        )
        end_setback = (
            radius * np.sqrt(np.maximum(0.0, 1.0 - c_end * c_end))
            / c_end
        )
        return float(np.min(lengths - start_setback - end_setback))

    def geometric_violation(self):
        """Worst normalized LOCAL validity violation; zero means locally valid.

        Checks radius positivity, nonzero legs, the turn cap, and overlap of the
        two mitre cuts on each leg. Exactness additionally requires no intersection
        between nonadjacent pipe pieces; this method deliberately does not use the
        overly conservative capsule test that rejects valid fine discretizations.
        """
        P = self.joints()
        rr = self.rr
        edges = np.roll(P, -1, axis=0) - P
        lengths = np.linalg.norm(edges, axis=-1)
        scale = max(1.0, float(np.max(lengths)), abs(rr))
        min_size = _MIN_RELATIVE_GEOMETRY_SIZE * scale

        u = edges / np.maximum(lengths[:, None], np.finfo(float).tiny)
        cos_turn = np.clip(
            np.sum(np.roll(u, 1, axis=0) * u, axis=-1),
            -1.0,
            1.0,
        )
        max_turn = float(np.degrees(np.arccos(cos_turn)).max())

        clearance = self.minimum_miter_clearance()
        radius_vio = max((min_size - rr) / scale, 0.0)
        edge_vio = float(np.max(np.maximum(min_size - lengths, 0.0)) / scale)
        turn_vio = max((max_turn - MAX_TURN_DEG) / MAX_TURN_DEG, 0.0)
        miter_vio = max(-clearance / scale, 0.0)
        return float(max(radius_vio, edge_vio, turn_vio, miter_vio))

    def eval(self, x, y, z):
        pts = np.concatenate((x.flatten()[:, None], y.flatten()[:, None],
                              z.flatten()[:, None]), axis=-1)
        return np.array(self.pure(pts, self.local_full_x, 1.0).astype(np.float32).reshape(x.shape))

    def rz_bounds(self):
        """Conservative bounds including the axial overhang of oblique mitres."""
        P = self.joints()
        B = np.roll(P, -1, axis=0)
        edges = B - P
        lengths = np.linalg.norm(edges, axis=-1)
        u = edges / np.maximum(lengths[:, None], np.finfo(float).tiny)

        sums = np.roll(u, 1, axis=0) + u
        miters = sums / np.maximum(
            np.linalg.norm(sums, axis=-1, keepdims=True),
            np.finfo(float).tiny,
        )
        c_start = np.clip(
            np.sum(u * miters, axis=-1),
            np.finfo(float).eps,
            1.0,
        )
        c_end = np.clip(
            np.sum(u * np.roll(miters, -1, axis=0), axis=-1),
            np.finfo(float).eps,
            1.0,
        )

        radius = abs(self.rr)
        start_setback = (
            radius * np.sqrt(np.maximum(0.0, 1.0 - c_start * c_start))
            / c_start
        )
        end_setback = (
            radius * np.sqrt(np.maximum(0.0, 1.0 - c_end * c_end))
            / c_end
        )
        extended_start = P - start_setback[:, None] * u
        extended_end = B + end_setback[:, None] * u
        axis_points = np.concatenate((extended_start, extended_end), axis=0)

        R_max = float(np.hypot(axis_points[:, 0], axis_points[:, 1]).max() + radius)
        Z_max = float(np.abs(axis_points[:, 2]).max() + radius)
        return R_max, Z_max

    def to_vtk(self, name, nx=60, ny=60, nz=40):
        R_max, Z_max = self.rz_bounds(); pad = 0.1
        xs = np.linspace(-(R_max + pad), R_max + pad, nx).astype(np.float32)
        ys = np.linspace(-(R_max + pad), R_max + pad, ny).astype(np.float32)
        zs = np.linspace(-(Z_max + pad), Z_max + pad, nz).astype(np.float32)
        X, Y, Z = np.meshgrid(xs, ys, zs, indexing="ij")
        pts = np.concatenate((X.flatten()[:, None], Y.flatten()[:, None],
                              Z.flatten()[:, None]), axis=-1)
        D = np.array(self.pure(pts, self.local_full_x, 1.0).astype(np.float32).reshape((nx, ny, nz)))
        gridToVTK(name, x=xs, y=ys, z=zs, cellData=None, pointData={"sdf": D})
